### ISSUE TITLE
Consider removing TrayIconSender

### ISSUE THREAD

**Issue by kmod-midori** [Ciantic/trayicon-rs#6]
Since #5 seems to be ignored (and updating `winit` every time is not really convenient), I suggest that we remove the `sender_*` functions entirely and provide a callback `F: Fn(T) -> ()` (where `T` is the event type). Since almost all existing message passing implementations (std, winit, and crossbeam) only takes `&self`, this would be fine. The final code would look like this:
```rust
let proxy = event_loop.create_proxy();
let mut tray_icon = TrayIconBuilder::new()
  .sender(move |e| { let _ = proxy.send(e.clone()); });
```
This completely eliminates the dependency on `crossbeam` and `winit`.

**Comment by Ciantic** [comment]
I updated winit now. 

Hmm, it sounds good, but what is wrong with the current non winit/crossbeam feature of using: [`std::sync::mpsc::Sender<T>`](https://github.com/Ciantic/trayicon-rs/blob/df3e276bc52bee844ef0ba7fa7783c7d790c0cf3/src/trayiconsender.rs#L7) in that case? Would lambda work better than mpsc::Sender?

**Comment by kmod-midori** [comment]
The lambda version makes the user responsible for actually sending the message using whatever method they want, which is more extensible than the current solution. At the same time, we don't need to update winit every time it is updated.

**Comment by Ciantic** [comment]
I merged the pull request that did it.
