### ISSUE TITLE
winit example not compiling

### ISSUE THREAD

**Issue by Nickiel12** [Ciantic/trayicon-rs#8]
When I try to run the Winit example (clone this repo, navigate to the winit example, and `cargo run`) I get 

mismatched types
expected struct `winit::event_loop::EventLoopProxy<Events>`
   found struct `EventLoopProxy<Events>`
perhaps two different versions of crate `winit` are being used?

**Comment by UndeRus** [comment]
Rollback to winit 0.25, it works

**Comment by Nickiel12** [comment]
that did the trick!
